# -*- coding: utf-8 -*-
class Constants:
    cst_isodate   = '%Y-%m-%d'
    cst_iso_dt_HM = '%Y-%m-%d %H:%M'
    cst_date_eu   = '%d/%m/%Y'
    cst_date_us   = '%m/%d/%Y'
    cst_date_ymd  = '%Y%m%d'
    cst_dt_HM     = '%Y-%m-%d %H:%M'
    cst_dt_eu_HM  = '%d/%m/%Y %H:%M'
    cst_dt_us_HM  = '%m/%d/%Y %H:%M'

    cst_dhis2     = '/storage/resource/dhis2/'
    cst_form_pat  = '/storage/resource/form/patient/'
    cst_epidemio  = '/storage/resource/epidemio/'
    cst_indicator = '/storage/resource/indicator/'
    cst_template  = '/storage/resource/template/'
    cst_photo     = '/storage/resource/photo/'
    cst_io        = '/storage/io/'
    cst_report    = '/storage/report/'
    cst_resource  = '/storage/resource/'
    cst_printer   = '/storage/resource/printer/'
    cst_upload    = '/storage/upload/'
    cst_path_tmp  = '/home/apps/labbook_BE/labbook_BE/tmp/'

    cst_connect_mapping = '/storage/resource/connect/analyzer/mapping'
    cst_connect_plugin  = '/storage/resource/connect/analyzer/plugin'
    cst_connect_setting = '/storage/resource/connect/analyzer/setting'
