# SonarCloud/SonarQube project properties
sonar.projectKey=fondationmerieux
sonar.organization=fondationmerieux
sonar.sources=labbook_FE,labbook_BE
sonar.exclusions=labbook_BE/alembic/**
sonar.python.version=3.11
