# -*- coding:utf-8 -*-
version = 1

# ----------------------------------------------------------------------------
# The description section defines the list of elements to be used in the form.
# ----------------------------------------------------------------------------
[description]

    [[description.form_element]]
    id = "label_identity"
    label = "Identité"
    type = "h6"

    [[description.form_element]]
    labbook_ref = "pat_ano"
    input_type = "radio"

    [[description.form_element]]
    labbook_ref = "pat_code_lab"
    input_type = "text"

    [[description.form_element]]
    labbook_ref = "pat_code"

    [[description.form_element]]
    labbook_ref = "pat_name"
    input_type = "text"

    [[description.form_element]]
    labbook_ref = "pat_midname"
    input_type = "text"

    [[description.form_element]]
    labbook_ref = "pat_maiden"
    input_type = "text"

    [[description.form_element]]
    labbook_ref = "pat_firstname"
    input_type = "text"

    [[description.form_element]]
    labbook_ref = "pat_sex"
    input_type = "radio"
    attr_required = true

    [[description.form_element]]
    labbook_ref = "pat_birth"
    input_type = "date"

    [[description.form_element]]
    labbook_ref = "pat_birth_approx"
    input_type = "radio"

    [[description.form_element]]
    id = "label_or"
    label = "ou"
    type = "span"

    [[description.form_element]]
    labbook_ref = "pat_age"
    input_type = "text"
    attr_required = true

    [[description.form_element]]
    labbook_ref = "pat_age_unit"
    input_type = "select"
    attr_required = true

    [[description.form_element]]
    labbook_ref = "pat_nationality"
    input_type = "select"

    [[description.form_element]]
    labbook_ref = "pat_resident"
    input_type = "radio"

    [[description.form_element]]
    labbook_ref = "pat_blood_group"
    input_type = "select"

    [[description.form_element]]
    labbook_ref = "pat_blood_rhesus"
    input_type = "select"

    [[description.form_element]]
    id = "label_contact_details"
    label = "Coordonnées"
    type = "h6"

    [[description.form_element]]
    labbook_ref = "pat_address"
    input_type = "textarea"

    [[description.form_element]]
    labbook_ref = "pat_phone1"
    input_type = "text"

    [[description.form_element]]
    labbook_ref = "pat_phone2"
    input_type = "text"

    [[description.form_element]]
    labbook_ref = "pat_profession"
    input_type = "text"

    [[description.form_element]]
    labbook_ref = "search_zipcity"

    [[description.form_element]]
    labbook_ref = "pat_pbox"
    input_type = "text"

    [[description.form_element]]
    labbook_ref = "pat_district"
    input_type = "text"

    [[description.form_element]]
    labbook_ref = "pat_zipcode"
    input_type = "text"

    [[description.form_element]]
    labbook_ref = "pat_city"
    input_type = "text"

# -----------------------------------------------------------------
# The layout section defines how elements are placed and displayed.
# -----------------------------------------------------------------
[layout]
    [[layout.rows]]
    class = "panel-heading row"
    elements = [ { element = "label_identity", class = "panel-title" } ]

    [[layout.rows]]
    class = "row mt-3"

        [[layout.rows.cols]]
        class = "col"
        elements = [ { element = "pat_ano", class = "flex-md-row" } ]
    
        [[layout.rows.cols]]
        class = "col-md-7"
        elements = [ { element = "pat_code_lab", class = "flex-md-row" } ]
    
        [[layout.rows.cols]]
        class = "col"
        elements = [ { element = "pat_code", class = "flex-md-row" } ]

    [[layout.rows]]
    class = "row"

        [[layout.rows.cols]]
        class = "col-md"
        elements = [ 
                { element = "pat_name", class = "flex-md-row" },
                { element = "pat_midname", class = "flex-md-row" },
                { element = "pat_maiden", class = "flex-md-row" },
                { element = "pat_firstname", class = "flex-md-row" },
                { element = "pat_sex", class = "flex-md-row" }
        ]

        [[layout.rows.cols]]
        class = "col-md"
        elements = [ 
                { element = "pat_birth", class = "flex-md-row" },
                { element = "pat_birth_approx", class = "flex-md-row" },
                { class = "d-md-flex", elements = [
                    { element = "label_or", class = "flex-md-row" },
                    { element = "pat_age", class = "flex-md-row" },
                    { element = "pat_age_unit", class = "flex-md-row" }
                    ] },
                { element = "pat_nationality", class = "flex-md-row" },
                { element = "pat_resident", class = "flex-md-row" },
                { class = 'd-md-flex', elements = [
                    { element = "pat_blood_group", class = "flex-md-row" },
                    { element = "pat_blood_rhesus", class = "flex-md-row" }
                    ] }
        ]
        
    [[layout.rows]]
    class = "panel-heading row"
    elements = [ { element = "label_contact_details", class = "panel-title" } ]

    [[layout.rows]]
    class = "row mt-3"

        [[layout.rows.cols]]
        class = "col-md"
        elements = [ 
                { element = "pat_address", class = "flex-md-row" },
                { element = "pat_phone1", class = "flex-md-row" },
                { element = "pat_phone2", class = "flex-md-row" },
                { element = "pat_profession", class = "flex-md-row" }
        ]

        [[layout.rows.cols]]
        class = "col-md"
        elements = [ 
                { element = "search_zipcity", class = "" },
                { element = "pat_pbox", class = "flex-md-row" },
                { element = "pat_district", class = "flex-md-row" },
                { element = "pat_zipcode", class = "flex-md-row" },
                { element = "pat_city", class = "flex-md-row" }
        ]
